//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreSolicitud
    {
        public int ID { get; set; }
        public int SolicitudIncidenciaID { get; set; }
        public bool Cerrada { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public string DatoRelacionado { get; set; }
    
        public virtual SolictudIncidencia SolictudIncidencia { get; set; }
    }
}
