//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estatu
    {
        public Estatu()
        {
            this.Departamentos = new HashSet<Departamento>();
            this.Personas = new HashSet<Persona>();
            this.TipoIncidencias = new HashSet<TipoIncidencia>();
            this.Usuarios = new HashSet<Usuario>();
            this.SolictudIncidencias = new HashSet<SolictudIncidencia>();
        }
    
        public int EstatusID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Departamento> Departamentos { get; set; }
        public virtual ICollection<Persona> Personas { get; set; }
        public virtual ICollection<TipoIncidencia> TipoIncidencias { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
        public virtual ICollection<SolictudIncidencia> SolictudIncidencias { get; set; }
    }
}
