//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolictudIncidencia
    {
        public int SolicitudIncidenciaID { get; set; }
        public System.DateTime FechaIncidencia { get; set; }
        public int DepartamentoID_Solicitud { get; set; }
        public int PersonaID_Solicitud { get; set; }
        public int TipoIncidenciaID { get; set; }
        public int PersonaID_Tecnico { get; set; }
        public string ComentariosSolicitud { get; set; }
        public int EstatusSolicitudID { get; set; }
        public int EstatusID { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Estatu Estatu { get; set; }
        public virtual EstatusSolicitud EstatusSolicitud { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
        public virtual TipoIncidencia TipoIncidencia { get; set; }
    }
}
