//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoIncidencia
    {
        public TipoIncidencia()
        {
            this.SolictudIncidencias = new HashSet<SolictudIncidencia>();
        }
    
        public int TipoIncidenciaID { get; set; }
        public string Descripcion { get; set; }
        public int EstatusID { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual Estatu Estatu { get; set; }
        public virtual ICollection<SolictudIncidencia> SolictudIncidencias { get; set; }
    }
}
