//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vIncidencias_Detalle
    {
        public int SolicitudIncidenciaID { get; set; }
        public string FechaIncidencia { get; set; }
        public int DepartamentoID_Solicitud { get; set; }
        public string DepartamentoSolicitud { get; set; }
        public int PersonaID_Solicitud { get; set; }
        public string CodigoPersonaSolicitud { get; set; }
        public string NombresPersonaSolicitud { get; set; }
        public string ApellidosPersonaSolicitud { get; set; }
        public int PersonaID_Tecnico { get; set; }
        public string CodigoPersonaTecnica { get; set; }
        public string NombresPersonaTecnica { get; set; }
        public string ApellidosPersonaTecnica { get; set; }
        public int TipoIncidenciaID { get; set; }
        public string TipoIncidenciaDescripcion { get; set; }
        public string ComentariosSolicitud { get; set; }
    }
}
